matrix:
  fast_finish: true
  allow_failures:
  - language: php
    php: 'master'
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php74
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php
  include:
  - language: php
    php: '7.1'
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: 'master'
  - language: nix
    env:
    - NIX_CHANNEL=18.09
    - NIX_PHP_ATTR=php71
  - language: nix
    env:
    - NIX_CHANNEL=19.03
    - NIX_PHP_ATTR=php72
  - language: nix
    env:
    - NIX_CHANNEL=19.03
    - NIX_PHP_ATTR=php73
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php74
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php

addons:
  apt:
    packages:
      - lcov

branches:
  only:
    - master
    - travis

before_install:
  - source ./.ci/travis_env.sh
  - before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
